#! /usr/bin/env python3
import argparse

def list_todo_list(display_all):
    with open('todo.txt', 'r') as todo_file:
        tasks = todo_file.readlines()
    
    counter = 0  
    for task in tasks:
        t = task.split('    ')
        todo = t[0]
        created = t[1]
        completed = t[2][:-1] if len(t)>2 else None
        if display_all:
            counter += 1
            print("{:3d} {}\nCreated: {}".format(counter, todo, created))
            if completed:
                print("Completed: {}\n".format(completed))
        else:
            if not completed:
                counter += 1
                print("{:3d} {}\nCreated: {}".format(counter, todo, created))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="List elements in todo-list")
    parser.add_argument("--all", "-a", action="store_true", help="When specified, list even completed tasks")
    args = parser.parse_args()
    list_todo_list(args.all)
