#! /usr/bin/env python3

import sys
import time
from datetime import datetime


def create_new_task(item):
    now = datetime.fromtimestamp(time.time()) 
    item_str = f"{item}    {now} \n"    
    with open('todo.txt', 'a+') as todo_file:
        todo_file.write(item_str)


if __name__ == '__main__':
    args = sys.argv
    task = args[1]
    create_new_task(task)

